# Executive Summary {.unnumbered}

::: justified
The National Spatial Plan is a strategic vision that defines the general trend and direction of spatial development for the country, covering the entire forty seven counties and the Exclusive Economic Zone (EEZ). It is a long term Plan spanning a period of thirty (30) years with 10 year periodical reviews. The preparation of the National Spatial Plan is recommended under the Kenya Vision 2030 as a flagship project under the Infrastructure Services sector as one of the foundations for socio-economic transformation.

 The purpose of the Plan is to provide a national spatial structure that defines how the national space is utilized to ensure optimal and sustainable use of land and land based resources. This is imperative as it will not only facilitate the attainment of national, social, economic and environmental goals and objectives but also the achievement of the national land policy principles of efficiency, equity, sustainability and productivity. Further, the Plan provides strategies and policies to deal with national challenges of regional imbalances/inequalities, rural development, underutilization of the available resources, urbanization, environmental degradation and inefficient transportation. 
 
In Kenya, the emphasis has hitherto been on economic planning with little or no regard for spatial/physical planning. This major disconnect has led to uncoordinated and unguided development resulting not only in duplication of efforts but also in resource wastage and unbalanced development. The Plan will thus provide a spatial framework upon which the various sectoral plans and policies will be anchored and coordinated. As a broad physical planning framework it will provide physical planning policies to support economic and sectoral planning and also guide the preparation of regional, county and local physical development plans.

 The specific objectives of the National Spatial Plan are:
 
- To create a spatial planning context that enhances economic efficiency and strengthens Kenya’s global 
competitiveness
- To promote balanced regional development for national integration and cohesion
- To optimize utilization of land and natural resources for economic development
- To create livable and functional human settlements for high quality of life in both urban and rural areas
- To secure the natural environment for sustainable development and
- To establish an integrated national transportation network and infrastructure system.

Further, the Plan aims to promote the principles of effective public participation, compact cities which entail delineating urban boundaries, smart and green urban growth to promote health and aesthetics, sustainable development for posterity, livability and efficiency among others.

The National Spatial Plan is organized into two sections. Part 1 (Chapters 1, 2 and 3) provides the introduction, the planning context and the country’s overall national development strategies. Part II (Chapters 4 and 5) provides the national spatial policy thrusts and the implementation framework for the National Spatial Plan. 

**Chapter 1** chronologically traces the historical perspectives of spatial planning efforts in Kenya. It also outlines the methodology applied in preparing the Plan, the rationale for preparing the Plan; the strategic direction as well as the constitutional, legal and policy basis for the Plan. 

**Chapter 2** takes a sectoral approach to situational analysis of the country’s spatial planning context. It gives a detailed review of the country’s geographical positioning, population dynamics, economic trends, resource endowment, land use patterns and practices, sector policies and plans as well as the aspirations of Kenyans as espoused in the Constitution. 

**Chapter 3** provides approaches and strategies for spatial growth and development of the country by identifying and exploiting the inherent resource potentials while addressing the factors that prevent the country from achieving the intended national goals and objectives. Thematic areas on global impacts, land use, regional balance, urbanization, environment, national transportation and infrastructure have been discussed and respective strategies formulated to address the identified issues.

**Chapter 4** presents the national spatial structure which aims at setting the direction of spatial development of the country to achieve pre-determined national goals and objectives. It also details the policies together with supporting measures for realizing the strategies formulated. These policies and measures are designed at promoting the achievement of the goals and objectives of NSP of enhancing the country’s competitiveness and economic efficiency, modernizing agriculture, diversifying tourism, supporting industrialization, creating functional and livable human settlements, conserving the environment, integrating the national transport network and providing quality infrastructure and services. 

**Chapter 5** proposes an implementation framework for the Plan which establishes institutions necessary for its realization, identifies activities to be undertaken together with the respective actors and spells out the timelines. 
Some of the broad action areas include the preparation of regional, county and local spatial plans to integrate and conform to the proposals of the NSP, assimilation of the proposed policies to the sector plans and programmes, formulation of regulations and standards to guide development and incorporation into the five year Medium Term Plan (MTPs).
:::
